BEGIN;

CREATE TABLE IF NOT EXISTS one_time_notifications
(
    db_id                   int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    dest_user_id            int8                                                                                                                     NOT NULL,
    notification_type       int4                                                                                                                     NOT NULL,
    notification_identifier varchar(255)                                                                                                             NOT NULL,
    created_at              timestamptz                                                                                                              NOT NULL DEFAULT now(),
    CONSTRAINT one_time_notifications_pkey PRIMARY KEY (db_id),
    CONSTRAINT one_time_notifications_dest_user_id FOREIGN KEY (dest_user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS notification_identifier_index ON one_time_notifications (dest_user_id, notification_type, notification_identifier);

COMMIT;

