BEGIN;
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS event_is_live bool NOT NULL DEFAULT false;
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS event_test_mode_enabled bool NOT NULL DEFAULT false;
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS event_is_public bool NOT NULL DEFAULT false;
COMMIT;