BEGIN;

create type upload_status as ENUM('PENDING', 'APPROVED', 'REJECTED');
create type upload_repost_permissions as ENUM('PHOTOGRAPHER_DISCRETION', 'CC_BY_NC_ND', 'CC_BY_NC', 'CC_BY_ND', 'CC_BY', 'PUBLIC_DOMAIN', 'ALL_RIGHTS_RESERVED');
create type upload_type as ENUM('IMAGE', 'VIDEO', 'UNKNOWN', 'UNPROCESSED');

CREATE TABLE IF NOT EXISTS upload_progress_info
(
    id                      int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    s3_upload_id            text                                                                                                                     NOT NULL,
    key_name                text                                                                                                                     NOT NULL,
    expire_ts               timestamp                                                                                                                NOT NULL DEFAULT NOW(),
    size                    int8                                                                                                                     NOT NULL,
    uploader_user_id        int8                                                                                                                     NOT NULL,
    CONSTRAINT upload_progress_info_pkey PRIMARY KEY (id),
    CONSTRAINT upload_progress_info_user FOREIGN KEY (uploader_user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT upload_progress_info_one_upload_per_user UNIQUE(uploader_user_id)
);

CREATE TABLE IF NOT EXISTS uploads
(
    id                        int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    original_uploader_user_id int8                                                                                                                     NOT NULL,
    photographer_user_id      int8                                                                                                                     NOT NULL,
    upload_timestamp          timestamptz                                                                                                              NOT NULL DEFAULT NOW(),
    shot_timestamp            timestamptz                                                                                                              NULL,
    status                    upload_status                                                                                                            NOT NULL DEFAULT 'PENDING',
    original_file_name        varchar(128)                                                                                                             NOT NULL,
    file_size                 int8                                                                                                                     NOT NULL,
    resolution_width          int4                                                                                                                     NOT NULL DEFAULT 0,
    resolution_heigth         int4                                                                                                                     NOT NULL DEFAULT 0,
    hash                      uuid                                                                                                                     NULL,
    upload_type               upload_type                                                                                                              NOT NULL DEFAULT 'UNPROCESSED',
    media_id                  int8                                                                                                                     NOT NULL,
    thumbnail_media_id        int8                                                                                                                     NULL,
    rendered_media_id         int8                                                                                                                     NULL,
    is_selected               bool                                                                                                                     NOT NULL DEFAULT false,
    repost_permissions        upload_repost_permissions                                                                                                NOT NULL,
    event_id                  int8                                                                                                                     NOT NULL,
    CONSTRAINT uploads_pkey PRIMARY KEY (id),
    CONSTRAINT uploads_unique_hash UNIQUE(hash),
    CONSTRAINT uploads_photographer_user FOREIGN KEY (photographer_user_id) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE, -- We don't want upload to be deleted if an user deletes his profile
    CONSTRAINT uploads_original_user FOREIGN KEY (original_uploader_user_id) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE, -- We don't want upload to be deleted if an user deletes his profile
    CONSTRAINT uploads_media_id FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE ON UPDATE CASCADE, -- If file media is deleted, it's fine to delete everything else. Thumbnail cleanup happens automatically
    CONSTRAINT uploads_thumbnail_media_id FOREIGN KEY (thumbnail_media_id) REFERENCES media (media_id) ON DELETE SET NULL ON UPDATE CASCADE, -- We don't want upload to be deleted if thumbnail gets deleted
    CONSTRAINT uploads_rendered_media_id FOREIGN KEY (rendered_media_id) REFERENCES media (media_id) ON DELETE SET NULL ON UPDATE CASCADE, -- We don't want upload to be deleted if rendered image gets deleted
    CONSTRAINT uploads_event_id FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE SET NULL ON UPDATE CASCADE -- We don't want upload to be deleted if event gets deleted
);

CREATE TABLE IF NOT EXISTS upload_exif
(
    id                 int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    upload_id          int8                                                                                                                     NOT NULL,
    camera_maker       varchar(128)                                                                                                             NULL,
    camera_model       varchar(128)                                                                                                             NULL,
    lens_maker         varchar(128)                                                                                                             NULL,
    lens_model         varchar(128)                                                                                                             NULL,
    focal              varchar(128)                                                                                                             NULL,
    shutter            varchar(128)                                                                                                             NULL,
    aperture           varchar(128)                                                                                                             NULL,
    iso                varchar(128)                                                                                                             NULL,
    CONSTRAINT upload_exif_pkey PRIMARY KEY (id),
    CONSTRAINT upload_exif_only_one_per_upload UNIQUE (upload_id),
    CONSTRAINT upload_exif_upload_id FOREIGN KEY (upload_id) REFERENCES uploads (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS upload_video_data
(
    id                 int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    upload_id          int8                                                                                                                     NOT NULL,
    video_codec        varchar(128)                                                                                                             NULL,
    audio_codec        varchar(128)                                                                                                             NULL,
    duration           int4                                                                                                                     NULL,
    framerate          varchar(128)                                                                                                             NULL,
    audio_frequency    varchar(128)                                                                                                             NULL,
    CONSTRAINT upload_video_data_pkey PRIMARY KEY (id),
    CONSTRAINT upload_video_data_only_one_per_upload UNIQUE (upload_id),
    CONSTRAINT upload_video_data_upload_id FOREIGN KEY (upload_id) REFERENCES uploads (id) ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE IF EXISTS media DROP CONSTRAINT IF EXISTS media_store_method_check;
ALTER TABLE IF EXISTS media ADD CONSTRAINT media_store_method_check CHECK (((media_store_method >= 0) AND (media_store_method <= 2)));

COMMIT;

