package net.furizon.backend.feature.pretix.objects.order.usecase;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.furizon.backend.feature.membership.action.createMembershipCard.CreateMembershipCardAction;
import net.furizon.backend.feature.membership.action.updateMembershipOwner.UpdateMembershipCardOwner;
import net.furizon.backend.feature.membership.dto.MembershipCard;
import net.furizon.backend.feature.membership.finder.MembershipCardFinder;
import net.furizon.backend.feature.pretix.objects.event.Event;
import net.furizon.backend.feature.pretix.objects.order.Order;
import net.furizon.backend.feature.pretix.objects.order.PretixOrder;
import net.furizon.backend.feature.pretix.objects.order.action.deleteOrder.DeleteOrderAction;
import net.furizon.backend.feature.pretix.objects.order.action.upsertOrder.UpsertOrderAction;
import net.furizon.backend.feature.user.finder.UserFinder;
import net.furizon.backend.infrastructure.email.EmailSender;
import net.furizon.backend.infrastructure.email.MailVarPair;
import net.furizon.backend.infrastructure.pretix.model.OrderStatus;
import net.furizon.backend.infrastructure.pretix.service.PretixInformation;
import net.furizon.backend.infrastructure.security.permissions.Permission;
import org.jetbrains.annotations.NotNull;
import org.springframework.stereotype.Component;

import java.util.Optional;

import static net.furizon.backend.feature.authentication.AuthenticationMailTexts.SUBJECT_FATAL_ERROR_MEMBERSHIP;
import static net.furizon.backend.feature.authentication.AuthenticationMailTexts.TEMPLATE_MEMBERSHIP_CARD_FATAL_ERROR;
import static net.furizon.backend.infrastructure.email.EmailVars.MEMBERSHIP_CARD_ID;
import static net.furizon.backend.infrastructure.email.EmailVars.MEMBERSHIP_CARD_ID_IN_YEAR;
import static net.furizon.backend.infrastructure.email.EmailVars.ORDER_CODE;
import static net.furizon.backend.infrastructure.email.EmailVars.ORDER_OWNER_ID;
import static net.furizon.backend.infrastructure.email.EmailVars.ORDER_PREV_OWNER_ID;

@Component
@RequiredArgsConstructor
@Slf4j
public class UpdateOrderInDb {
    @NotNull private final UpsertOrderAction upsertOrderAction;
    @NotNull private final DeleteOrderAction deleteOrderAction;
    @NotNull private final CreateMembershipCardAction createMembershipCardAction;
    @NotNull private final UpdateMembershipCardOwner updateMembershipCardOwner;
    @NotNull private final MembershipCardFinder membershipCardFinder;
    @NotNull private final EmailSender emailSender;
    @NotNull private final UserFinder userFinder;

    public @NotNull Optional<Order> execute(@NotNull PretixOrder pretixOrder,
                                             @NotNull Event event,
                                             @NotNull PretixInformation pretixInformation) {
        Order order = null;
        boolean shouldDelete = true;

        var orderOpt = pretixInformation.parseOrder(pretixOrder, event);
        if (orderOpt.isPresent()) {
            order = orderOpt.get();
            OrderStatus os = order.getOrderStatus();
            if (os == OrderStatus.PENDING || os == OrderStatus.PAID) {
                log.debug("[PRETIX] Storing / Updating order: {}@{}", pretixOrder.getCode(), event.getSlug());
                upsertOrderAction.invoke(order, pretixInformation);

                // GENERATE MEMBERSHIP CARD LOGIC
                Long orderOwnerId = order.getOrderOwnerUserId();
                if (orderOwnerId != null) {
                    MembershipCard card = membershipCardFinder.getMembershipCardByOrderId(order.getId());

                    if (card == null) { // No membership card has been generated by this order
                        if (userFinder.findById(orderOwnerId) != null) {
                            log.info("[PRETIX] Generating new membership card for user {}", orderOwnerId);
                            createMembershipCardAction.invoke(orderOwnerId, event, order);
                        } else {
                            log.warn("[PRETIX] Tried generating card for user {}, but it doesn't exist in the DB",
                                    orderOwnerId);
                        }

                    } else { //A membership card was already created with this order
                        Long cardOwnerId = card.getCreatedForOrderId();

                        if (cardOwnerId != null && !cardOwnerId.equals(orderOwnerId)) { //Order owner has changed
                            if (!card.isRegistered()) { //If the card was not registered yet, we can change the owners
                                log.warn("[PRETIX] Order {} has already generated the membeship card {}/{}. "
                                        + "However, the order owner has changed ({} -> {}) and, since the card "
                                        + "was not registered yet, the card's owner is now changed as well",
                                    order.getCode(),
                                    card.getCardId(), card.getIdInYear(),
                                    cardOwnerId, orderOwnerId
                                );
                                updateMembershipCardOwner.invoke(card, orderOwnerId);

                            } else { //Otherwise, send an error email to web admins
                                log.error("[PRETIX] Order {} has already generated the membeship card {}/{}. "
                                        + "Order owner has changed ({} -> {}), "
                                        + "but membership card was already registered!!"
                                        + "Manual fix is needed!!! +++",
                                    order.getCode(),
                                    card.getCardId(), card.getIdInYear(),
                                    cardOwnerId, orderOwnerId
                                );

                                emailSender.sendToPermission(
                                        Permission.CAN_MANAGE_MEMBERSHIP_CARDS,
                                        SUBJECT_FATAL_ERROR_MEMBERSHIP,
                                        TEMPLATE_MEMBERSHIP_CARD_FATAL_ERROR,
                                        MailVarPair.of(ORDER_CODE, order.getCode()),
                                        MailVarPair.of(MEMBERSHIP_CARD_ID, String.valueOf(card.getCardId())),
                                        MailVarPair.of(MEMBERSHIP_CARD_ID_IN_YEAR, String.valueOf(card.getIdInYear())),
                                        MailVarPair.of(ORDER_PREV_OWNER_ID, String.valueOf(cardOwnerId)),
                                        MailVarPair.of(ORDER_OWNER_ID, String.valueOf(orderOwnerId))
                                );
                            }
                        }
                    }
                }

                shouldDelete = false;
            } else {
                order = null;
            }
        } else {
            log.error("[PRETIX] Unable to parse order: {}@{}", pretixOrder.getCode(), event.getSlug());
        }

        if (shouldDelete) {
            deleteOrderAction.invoke(pretixOrder.getCode());
        }

        return Optional.ofNullable(order);
    }
}
