server:
  port: ${BACKEND_SERVER_PORT:9090}

spring:
  application:
    name: fz-backend
  datasource:
    url: ${BACKEND_DATASOURCE_URL:jdbc:postgresql://localhost:5432/furizon}
    username: ${BACKEND_DATASOURCE_USERNAME:user}
    password: ${BACKEND_DATASOURCE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres

logbook:
  format:
    style: http
  httpclient:
    decompress-response: true

pretix:
  url: ${PRETIX_BASE_URL:http://localhost:8000}
  apiPath: ${PRETIX_API_PATH:/api/v1/}
  api-key: ${PRETIX_API_KEY:OwO}
  default-organizer: ${PRETIX_DEFAULT_ORGANIZER:org}
  default-event: ${PRETIX_DEFAULT_EVENT:evnt}
  connection-timeout: ${PRETIX_HTTP_CLIENT_CONNECTION_TIMEOUT:10000}
