server:
  port: ${BACKEND_SERVER_PORT:9090}

spring:
  jpa:
    open-in-view: false
  application:
    name: fz-backend
  datasource:
    url: ${BACKEND_DATASOURCE_URL:jdbc:postgresql://localhost:5432/furizon}
    username: ${BACKEND_DATASOURCE_USERNAME:user}
    password: ${BACKEND_DATASOURCE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres

logbook:
  format:
    style: http
  httpclient:
    decompress-response: true

security:
  password-salt: ${SECURITY_HASHED_PASSWORD_SALT:changeit}
  token-secret-key: ${SECURITY_TOKEN_SECRET_KEY:a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6} #must be 32 bytes
  session:
    expiration: ${SECURITY_SESSION_EXPIRATION_DURATION:1d}

pretix:
  url: ${PRETIX_BASE_URL:http://localhost:8000}
  apiPath: ${PRETIX_API_PATH:/api/v1/}
  api-key: ${PRETIX_API_KEY:OwO}
  default-organizer: ${PRETIX_DEFAULT_ORGANIZER:org}
  default-event: ${PRETIX_DEFAULT_EVENT:event}
  connection-timeout: ${PRETIX_HTTP_CLIENT_CONNECTION_TIMEOUT:10000}
  enable-sync: ${PRETIX_ENABLE_INIT_SYNC:true}
