server:
  port: ${BACKEND_SERVER_PORT:9090}

spring:
  threads:
    virtual:
      enabled: true
  thread-executor: virtual
  jpa:
    open-in-view: false
  application:
    name: fz-backend
  datasource:
    url: ${BACKEND_DATASOURCE_URL:jdbc:postgresql://localhost:5432/furizon}
    username: ${BACKEND_DATASOURCE_USERNAME:user}
    password: ${BACKEND_DATASOURCE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres

logbook:
  format:
    style: http
  httpclient:
    decompress-response: true

springdoc:
  api-docs:
    path: /docs/api-docs
    enabled: ${DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${DOCS_ENABLED:false}

security:
  password-salt: ${SECURITY_HASHED_PASSWORD_SALT:changeit}
  token-secret-key: ${SECURITY_TOKEN_SECRET_KEY:a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6} #must be 32 bytes
  allowed-origins: ${SECURITY_ALLOWED_ORIGINS:["*"]} # TODO -> Only for dev
  session:
    expiration: ${SECURITY_SESSION_EXPIRATION_DURATION:1d}
    core-pool-update-size: ${SECURITY_SESSION_CORE_POOL_UPDATE_SIZE:6}
    max-allowed-sessions-size: ${SECURITY_SESSION_MAX_ALLOWED_SESSIONS_SIZE:4}

membership:
  card-enumeration-reset-month: ${MEMBERSHIPCARD_ENUMARATION_RESET_MONTH:10}
  card-enumeration-reset-day: ${MEMBERSHIPCARD_ENUMARATION_RESET_DAY:1}

frontend:
  login-redirect-url: ${FRONTEND_LOGIN_REDIRECT_URL:}
  order-homepage-url: ${FRONTEND_ORDER_HOMEPAGE_URL:}

room:
  logic: ${ROOM_LOGIC:roomLogic-default}

pretix:
  event:
    public-booking-start-time: ${PRETIX_EVENT_START_PUBLIC_BOOKING_TIME:}
    edit-booking-end-time: ${PRETIX_EVENT_EDIT_BOOKING_END_TIME:}
  enable-sync: ${PRETIX_ENABLE_INIT_SYNC:true}
  default-organizer: ${PRETIX_DEFAULT_ORGANIZER:org}
  default-event: ${PRETIX_DEFAULT_EVENT:event}
  api:
    url: ${PRETIX_API_URL:http://localhost:8000}
    path: ${PRETIX_API_PATH:/api/v1/}
    key: ${PRETIX_API_KEY:OwO}
  connection-timeout: ${PRETIX_HTTP_CLIENT_CONNECTION_TIMEOUT:10000}
  cache-reload-cronjob: ${PRETIX_CACHE_RELOAD_CRONJOB:0 0 0 * * *}
  shop:
    host: ${PRETIX_SHOP_HOST:localhost}
    port: ${PRETIX_SHOP_PORT:8000}
    base-path: ${PRETIX_SHOP_BASE_PATH:}
    path: ${pretix.shop.base-path}/${pretix.default-organizer}/${pretix.default-event}/
    url: https://${pretix.shop.host}:${pretix.shop.port}${pretix.shop.path}
  autocart:
    priv-key-path: ${PRETIX_AUTOCART_KEY_PATH:priv-key-autocart.rsa}
    priv-key-password: ${PRETIX_AUTOCART_KEY_PASSWORD:}