server:
  port: ${BACKEND_SERVER_PORT:8080}

spring:
  application:
    name: backend
  datasource:
    url: ${BACKEND_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${BACKEND_DATASOURCE_USERNAME:postgres}
    password: ${BACKEND_DATASOURCE_PASSWORD:postgres}

pretix:
  host: ${BACKEND_PRETIX_HOST:0.0.0.0}
  port: ${BACKEND_PRETIX_PORT:4321}
  secret: ${BACKEND_PRETIX_SECRET:AAAAAAAAAAAAAAAAA}
