package net.furizon.backend.feature.authentication;

public enum AuthenticationCodes {
    EMAIL_ALREADY_REGISTERED,
    EMAIL_NOT_REGISTERED,
    EMAIL_INVALID,
    INVALID_CREDENTIALS,
    AUTHENTICATION_IS_DISABLED,
    REGION_NOT_PROVIDED,
    REGION_INVALID,
    COUNTRY_INVALID,
    PHONE_PREFIX_INVALID,
    CONFIRMATION_NOT_FOUND,
    CONFIRMATION_SUCCESSFUL,
    CONFIRMATION_STILL_PENDING,
    ALREADY_LOGGED_IN,
    PW_RESET_STILL_PENDING,
    PW_RESET_NOT_FOUND,
    PW_CHAGE_SAME_PASSWORD,
    MEMBERSHIP_CARD_ORDER_STILL_LINKED,
    MEMBERSHIP_CARD_WAS_REGISTERED,
    MEMBERSHIP_NOT_FOUND,
    SESSION_NOT_YOURS, // Someone tried deleting someone else's session
    ID_EXPIRED,
    AGE_REQUIREMENT_FAIL
}
