package net.furizon.backend.feature.authentication;

public enum AuthenticationCodes {
    EMAIL_ALREADY_REGISTERED,
    EMAIL_NOT_REGISTERED,
    EMAIL_INVALID,
    INVALID_CREDENTIALS,
    AUTHENTICATION_IS_DISABLED,
    REGION_NOT_PROVIDED,
    CONFIRMATION_NOT_FOUND,
    CONFIRMATION_SUCCESSFULL,
    ALREADY_LOGGED_IN,
    PW_RESET_STILL_PENDING,
    PW_RESET_NOT_FOUND
}
