# This workflow performs a static analysis of your Java source code using
# CheckStyle.
#
# Scans are triggered:
# 1. On every push to default and protected branches
# 2. On every Pull Request targeting the default branch
# 3. On a weekly schedule
# 4. Manually, on demand, via the "workflow_dispatch" event
#
name: CheckStyle

on:
  # Triggers the workflow on push or pull request events but only for default and protected branches
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/checkstyle-analysis.yml"
      - "src/**"
      - "pom.xml"
  pull_request:
    branches: [ master ]
    paths:
      - ".github/workflows/checkstyle-analysis.yml"
      - "src/**"
      - "pom.xml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CheckStyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "adopt"
          cache: maven
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
      - name: Check
        run: ./mvnw checkstyle:check
